import 'models.dart';

final List<Customer> dummyCustomers = [
  Customer(
    fullName: 'Ahmed Youssef',
    phoneNumber: '01012345678',
    city: 'Cairo',
    region: 'Nasr City',
    productsInterested: ['Smartwatch', 'Wireless Earbuds'],
    interestLevel: InterestLevel.hotLead,
    interactionDateTime: DateTime.parse('2025-06-16T10:30:00'),
    contactPlatform: 'WhatsApp',
  ),
  Customer(
    fullName: 'Mariam Hany',
    phoneNumber: '01123456789',
    city: 'Alexandria',
    region: 'Smouha',
    productsInterested: ['Skincare Set'],
    interestLevel: InterestLevel.warm,
    interactionDateTime: DateTime.parse('2025-06-15T15:45:00'),
    contactPlatform: 'Instagram',
  ),
  Customer(
    fullName: 'Mostafa Khaled',
    phoneNumber: '01234567890',
    city: 'Giza',
    region: 'Haram',
    productsInterested: ['Laptop Bag'],
    interestLevel: InterestLevel.notInterested,
    interactionDateTime: DateTime.parse('2025-06-17T13:00:00'),
    contactPlatform: 'Facebook',
  ),
  Customer(
    fullName: 'Sarah Magdy',
    phoneNumber: '01567891234',
    city: 'Mansoura',
    region: 'El Gamaa',
    productsInterested: ['Makeup Kit', 'Mirror Light'],
    interestLevel: InterestLevel.warm,
    interactionDateTime: DateTime.parse('2025-06-14T17:20:00'),
    contactPlatform: 'Messenger',
  ),
  Customer(
    fullName: 'Tamer Adel',
    phoneNumber: '01098765432',
    city: 'Tanta',
    region: 'El Gharbia',
    productsInterested: ['Wireless Mouse'],
    interestLevel: InterestLevel.hotLead,
    interactionDateTime: DateTime.parse('2025-06-17T09:10:00'),
    contactPlatform: 'Instagram',
  ),
];
